### PR TITLE
[#10] Added Installation and Usage and Demo GIF to Readme

### PR DESCRIPTION
**Pull request by ameybhavsar24**
For #10

### CODE REVIEW

**Comment by ameybhavsar24** [comment]
@stephin007 Can you review and merge?

**Comment by stephin007** [comment]
@ameybhavsar24  let me check first!
Can you attach a screenshot of the readme, to check how it's looking!

**Comment by ameybhavsar24** [comment]
> @ameybhavsar24 let me check first!
> Can you attach a screenshot of the readme, to check how it's looking!

@stephin007 You can just check my fork at https://github.com/ameybhavsar24/githubfinder/blob/ameybhavsar24/testcase/README.md/README.md

**Comment by stephin007** [comment]
@ameybhavsar24 Its merged now, thanks for contributing :)

**Pull request merged**
